services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bolao-backend
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      TZ: America/Sao_Paulo
    profiles:
      - prod

  app-dev:
    image: node:22-alpine
    container_name: bolao-backend-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    network_mode: host
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      TZ: America/Sao_Paulo
    command: sh -c "npm install && npx prisma generate && npm run start:dev"
    profiles:
      - dev
