sonar.projectKey=cristianogomesalbino_bolao-backend
sonar.organization=cristianogomesalbino

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8